Adding the possibility to run a separate wallet
phoreproject/openbazaar-go pull request #12
Opened 2018-01-26 12:40 UTC by diofeher

2018-01-26 17:17 UTC, meyer9 requested changes
two small changes

2018-01-26 17:17 UTC, meyer9 commented on bitcoin/phored/wallet.go
> -	w.shutdownIfActive()
This should shut down only if we *aren't* using a separate wallet. If we are using a separate wallet, we don't want to shut down the current one.

2018-01-26 17:17 UTC, meyer9 commented on bitcoin/phored/wallet.go
> +		args = append(args, "-listen=0", "-datadir="+w.repoPath+"/wallet/", "-rpcuser="+connCfg.User, "-rpcpassword="+connCfg.Pass)
use path.Join

2018-01-26 17:37 UTC, diofeher commented
Done! @meyer9

2018-01-28 18:38 UTC, meyer9 approved these changes

2018-01-28 19:11 UTC, meyer9 commented
Merged in c03e3466157ce1251053addf51c2b3447e7dcdcd. Make sure to allow edits from maintainers in the future.

2018-01-28 19:11 UTC, closed without merging